modLoader="javafml"
loaderVersion="[33,)"
license="ARR"

[[mods]]
modId="fruittrees"
version="${file.jarVersion}"
displayName="Fruit Trees"
authors="Snownee, WZD, MalayP, minzhi"
displayURL="https://www.curseforge.com/minecraft/mc-mods/fruit-trees"
description=""
license="ARR"

[[dependencies.fruittrees]]
    modId="kiwi"
    mandatory=true
    versionRange="[3.5, 3.11)"
    ordering="BEFORE"
    side="BOTH"

[modproperties.fruittrees]
    catalogueItemIcon="fruittrees:grapefruit" #Support for Catalogue mod
    farmersdelightPantryCompat=[ "fruittrees:citrus_pantry", "fruittrees:cherry_pantry" ]
